name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: dd0870
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: dd0870/python-microservices-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: dd0870/python-microservices-frontend:latest

      - name: Build and push logger
        uses: docker/build-push-action@v4
        with:
          context: .
          file: logger/Dockerfile
          push: true
          tags: dd0870/python-microservices-logger:latest

      - name: Send failure alert
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "❌ GitHub Actions Pipeline Failed"
          to: ${{ secrets.EMAIL_USER }}
          from: DevOps Assignment CI/CD
          body: "The CI/CD pipeline failed. Please check GitHub Actions logs."
